CREATE TABLE `mes`.`department` (
  `id` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `user_id` VARCHAR(45) NULL DEFAULT '部门负责人',
  `created_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `updated_at` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE);
